version: "3"
services: 
  # api:
  #   image: openresty/openresty:alpine
  #   volumes:
  #   - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
  #   - "./demoapps:/opt/demoapps"
  #   ports:
  #   - "80:80"
  #   - "8080:8080"
  api2:
    image: nginx:latest
    volumes:
    - "./nginx.conf:/etc/nginx/nginx.conf"
    - "./demoapps:/opt/demoapps"
    ports:
    - "80:80"
    - "8080:8080"